# Row 9 of the PTO Liability at 08/31/2026 rubric - generated by build/build_package_artifacts.py, never edited here.
# Criterion: States, on the PTO liability page, a PTO liability of $8,187.68 for Finance and Corporate.
# Target app: wiki, check kind line_total
SPEC = {'criterion': 'States, on the PTO liability page, a PTO liability of $8,187.68 for Finance and '
              'Corporate.',
 'expected': [8187.68, 8185.08],
 'key': 'Finance and Corporate',
 'kind': 'line_total',
 'page': 'PTO Liability - 08/31/2026',
 'target': 'wiki'}

# ---- Engine, built to the app-db-verifier skill. The builder stamps SPEC on top: one row file,
# ---- one check(ctx). Edit here, never a row file. Content Match, and one Existence Check.
# R1 SELECT * only, columns by content or by the validated Wiki.js layout. R3 a figure counts only
# in the asked unit, by its own $ or hours, else its column header, else its prose line. R5 the
# title, an employee key and a line label match whole-field. R12 details say what was read.
# R15 never raises. Strikethrough is dropped. Two pages under the title fail. The platform's AST
# gate rejects os (09/23/2026); the harness sets QUIET. The graded dump carries no Wiki.js table
# (09/23/2026), so with no pages table the page is the run's own record of what the app accepted:
# the last successful create or update under the title, or the app's get_page reply. Never prose.
import json
import re

QUIET = False
PAGES_COLS = ["id", "path", "hash", "title", "description", "isPrivate", "isPublished",
              "privateNS", "publishStartDate", "publishEndDate", "content", "render", "toc",
              "contentType", "createdAt", "updatedAt", "editorKey", "localeCode", "authorId",
              "creatorId", "extra"]
TOL = {"total": 0.5, "line_total": 0.5, "hours": 0.05, "line_hours": 0.05}
MONEY_CUE, HOUR_CUE = r"\$|liabilit|dollar|usd", r"\bhours?\b|\bhrs?\b"
ID_RE = r"(?:trt|ctr)-\d{4}"
NUM_RE = re.compile(r"(\$\s?)?(?<![\w.,])(\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?)(?![\d,]*\d)"
                    r"(\s*(?:hours?|hrs?|usd|dollars)\b)?", re.I)


def _text(v):
    return "" if v is None else str(v)


def _norm(s):
    s = re.sub("[%s]" % (chr(0x2013) + chr(0x2014) + chr(0x2212)), "-", _text(s))
    return re.sub(r"\s+", " ", re.sub(r"[*_`]+", "", s)).strip().lower()


def _clean(raw):
    """Markup out, strikethrough dropped, table rows kept as rows."""
    s = _text(raw).replace("\\n", "\n")
    s = re.sub(r"<(?:del|s|strike)\b[^>]*>.*?</(?:del|s|strike)\s*>", " ", s, flags=re.I | re.S)
    s = re.sub(r"~~.*?~~", " ", s, flags=re.S)
    s = re.sub(r"</(?:td|th)\s*>", " | ", s, flags=re.I)
    if re.search(r"<tr\b", s, re.I):  # an HTML row starts a line; source newlines between rows are not blank lines
        s = re.sub(r"</(?:td|th)\s*>\s*</tr>\s*", "</td>", s, flags=re.I)
    s = re.sub(r"\s*<tr\b[^>]*>", "\n| ", s, flags=re.I)
    s = re.sub(r"</(?:table|p|div|li|h[1-6])\s*>|<br\s*/?>", "\n", s, flags=re.I)  # a row ends at the next <tr>
    s = re.sub(r"<[^>]+>", " ", s).replace("&nbsp;", " ").replace("&amp;", "&")
    s = re.sub(r"&(?:ndash|mdash|minus);", "-", s)
    return "\n".join(l.strip() for l in re.sub(r"[ \t]+", " ", s).split("\n")).strip()


def _label(s):
    """A line label as compared: an ampersand read as and, a trailing total or subtotal dropped."""
    n = re.sub(r"[:.]+$", "", _norm(s).replace("&", " and ")).strip()
    return re.sub(r"\s+", " ", re.sub(r"\s+(total|subtotal|line)$", "", n)).strip()


def _keyed(cells):
    return any(re.fullmatch(ID_RE + r"(?: \(.*\))?", _norm(c)) for c in cells)


def _figures(text, unit_hint, want):
    """The numbers in text read in the unit `want` ("money" or "hours"). A number's own $ or hours
    decides; a bare number takes unit_hint, the column header's or the line's single unit cue."""
    out = []
    for m in NUM_RE.finditer(text):
        tail = (m.group(3) or "").strip().lower()
        unit = "money" if m.group(1) or tail in ("usd", "dollars") else "hours" if tail else unit_hint
        if unit == want:
            out.append(float(m.group(2).replace(",", "")))
    return out


def _hint(text):
    money, hours = re.search(MONEY_CUE, text, re.I), re.search(HOUR_CUE, text, re.I)
    return "money" if money and not hours else "hours" if hours and not money else None


def _sources(body):
    """(where, text, unit_hint, cells) for every prose line and every table row keyed on no
    employee; a cell's hint is its column header's. Employee rows are never a source."""
    out, header = [], None
    for line in body.split("\n"):
        if line.count("|") < 2:
            header = None  # a blank or prose line ends a table, as markdown reads it
            if line.strip():
                out.append(("prose", line, _hint(line), None))
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if all(re.fullmatch(r":?-{2,}:?", c or "--") for c in cells):
            continue
        if header is None:
            header = cells
            continue
        if not _keyed(cells):
            hints = [_hint(header[i]) if i < len(header) else None for i in range(len(cells))]
            out.append(("row", line, None, list(zip(cells, hints))))
    return out


def _stated(body, kind, key, notes):
    want = "money" if kind in ("total", "line_total") else "hours"
    found, lab = [], _label(key) if key else None
    for where, text, hint, cells in _sources(body):
        if where == "prose":
            n = re.sub(r"\s+", " ", re.sub(r"^[#>*\-\s]+", "", _norm(text)).replace("&", " and "))
            if lab and not (n.startswith(lab) and not re.match(r"[a-z]|\s*(and|&)\s", n[len(lab):])):
                continue
            got = _figures(text.replace(key, " ") if key else text, hint, want)
        else:
            if lab and not any(_label(c) == lab for c, h in cells):
                continue
            got = [x for c, h in cells if not (lab and _label(c) == lab) for x in _figures(c, h, want)]
        if got:
            notes.append("%s %r read as %s: %r" % (where, text[:100], want, got))
        found += got
    return found


def _pages(ctx, notes):
    names = list(ctx.list_tables())
    notes.append("tables in the snapshot: %r" % names)
    name = next((n for n in names if n.lower() == "pages"), None) or next(
        (n for n in names if "page" in n.lower() and not any(
            x in n.lower() for x in ("history", "tree", "link", "tag", "meta"))), None)
    if not name:
        notes.append("no pages table in this snapshot; reading the run's Wiki.js calls")
        return _traj(ctx, notes)
    cols, rows = list(ctx.table_columns(name)), [list(r) for r in ctx.query_db("SELECT * FROM %s" % name)]
    real = "title" in cols and "content" in cols
    notes.append("table %s: %d columns %r, %d rows, %s column names"
                 % (name, len(cols), cols, len(rows), "real" if real else "placeholder"))
    found = []
    for n, r in enumerate(rows):
        hits = [i for i, v in enumerate(r) if _norm(v) == _norm(SPEC["page"])]
        if not hits:
            continue
        if real and cols.index("title") in hits:
            body, pub, route = r[cols.index("content")], r[cols.index("isPublished")] if "isPublished" in cols else None, "real names"
        elif not real and len(r) == len(PAGES_COLS) and 3 in hits:
            body, pub, route = r[10], r[6], "documented layout, the title at index 3 of %d" % len(r)
        elif not real:
            cand = [v for v in r if isinstance(v, str) and ("|" in v or "#" in v) and len(v) > 40]
            body, pub, route = max(cand, key=len) if cand else "", None, "longest table-bearing cell"
        else:
            notes.append("page row %d carries the title outside its title column; not this page" % n)
            continue
        pub = None if pub is None else _norm(pub) in ("1", "true", "t", "yes", "y")
        notes.append("page row %d matches via %s, published=%r" % (n, route, pub))
        found.append((_clean(body), pub))
    return found


def _load(v):
    if isinstance(v, list) and all(isinstance(x, dict) and "text" in x for x in v):
        v = "".join(_text(x["text"]) for x in v)
    try:
        return json.loads(v) if isinstance(v, str) and v.strip()[:1] in "{[" else v
    except ValueError:
        return v


def _traj(ctx, notes):
    t = _load(getattr(ctx, "trajectory", None))
    t = next((_load(t[k]) for k in ("trajectory_messages", "messages") if k in t), []) if isinstance(t, dict) else t
    t = [m for m in (t if isinstance(t, list) else []) if isinstance(m, dict)]
    notes.append("trajectory: %d messages, keys %r" % (len(t), sorted({k for m in t for k in m})[:12]))
    res = {m.get("tool_call_id"): _load(m.get("content")) for m in t if m.get("role") == "tool"}
    ids, pages, obs = set(), {}, []
    for tc in [c for m in t for c in (m.get("tool_calls") or []) if isinstance(c, dict)]:
        fn = tc.get("function") or tc
        name, a, r = _text(fn.get("name")), _load(fn.get("arguments") or {}), res.get(tc.get("id"))
        a = a.get("request") if isinstance(a, dict) and isinstance(a.get("request"), dict) else a
        if "wiki" not in name or not isinstance(a, dict) or not isinstance(r, dict):
            continue
        p = r.get("page") if name.endswith("get_page") and isinstance(r.get("page"), dict) else None
        if p and _norm(p.get("title")) == _norm(SPEC["page"]):
            ids.add(_text(p.get("id")))
            obs.append((name, p.get("id"), p.get("content"), p.get("is_published", p.get("isPublished"))))
        elif name.endswith(("create_page", "update_page")) and r.get("success") is True:
            pid = _text(r.get("page_id", a.get("id", a.get("page_id"))))
            if _norm(a.get("title")) == _norm(SPEC["page"]) or (name.endswith("update_page") and pid in ids):
                ids.add(pid)
                pages[pid] = pages.get(pid, 0) + name.endswith("create_page")
                obs.append((name, pid, a.get("content"), a.get("is_published")))
    body = next((o for o in reversed(obs) if o[2] is not None), None)
    pub = next((o[3] for o in reversed(obs) if o[3] is not None), None)
    notes.append("Wiki.js calls on the page: %r" % [(o[0][-11:], o[1]) for o in obs][:12])
    if body is None:
        return []
    pub = None if pub is None else _norm(pub) in ("1", "true", "t", "yes", "y")
    return [(_clean(body[2]), pub)] * max(1, sum(1 for v in pages.values() if v))


def check(ctx):
    notes, metrics = [], {}

    def out(passed, line):
        details = "\n".join(notes + ["", ("PASSED - " if passed else "FAILED - ") + line])
        if not QUIET:
            print(details)
        return {"passed": passed, "details": details, "metrics": metrics}

    try:
        pages = _pages(ctx, notes)
        metrics["page_rows"] = len(pages)
        if not pages:
            return out(False, "no page titled %r" % SPEC["page"])
        if len(pages) > 1:
            return out(False, "%d page rows carry the title %r; the request asks for one" % (len(pages), SPEC["page"]))
        body, pub = pages[0]
        if SPEC["kind"] == "exists":
            if pub is None:
                return out(False, "the published flag could not be read, so publication is not shown")
            return out(pub, "published=%r" % pub)
        figures = _stated(body, SPEC["kind"], SPEC.get("key"), notes)
        tol = TOL[SPEC["kind"]]
        metrics["figures_read"] = len(figures)
        hits = [x for x in figures if any(abs(x - t) <= tol for t in SPEC["expected"])]
        notes.append("expected one of %r within %s" % (SPEC["expected"], tol))
        if hits:
            return out(True, "stated %s %.2f" % (SPEC.get("key") or SPEC["kind"], hits[0]))
        return out(False, "the page states %r and none is the %s" % (figures[:8], SPEC.get("key") or SPEC["kind"]))
    except Exception as exc:
        notes.append("unexpected error: %s: %s" % (type(exc).__name__, str(exc)[:300]))
        return out(False, "the check could not complete; see the error above")
