# Row 30 of the PTO Liability Schedule and BambooHR PTO Records rubric - generated by build/build_package_artifacts.py, never edited here.
# Criterion: States, on the PTO liability page, a balance of 62.62 hours for Sora Jackson, TRT-0002.
# Target app: wiki, check kind balance
SPEC = {'criterion': 'States, on the PTO liability page, a balance of 62.62 hours for Sora Jackson, '
              'TRT-0002.',
 'expected': [62.62, 62.6],
 'key': 'TRT-0002',
 'kind': 'balance',
 'page': 'PTO Liability - 08/31/2026',
 'target': 'wiki'}

# ---- verifier engine. The builder prepends `SPEC = {...}` to this file to make one standalone
# ---- check(ctx) per rubric row, written to qc/verifiers/. Edit the engine here, never a row file.
#
# What keeps it honest, in the order the app-db-verifier skill lists them:
#   * it reads the grading database and nothing else - no files, no trajectory, no final answer;
#   * it never names a column in SQL; a table's columns are resolved by content, or by a documented
#     layout only when the row's shape validates, and the route taken is written into details;
#   * the page is found by its TITLE on a whole-field match, dashes and case normalised;
#   * an employee row is found by a WHOLE-CELL match on the employee ID, never a substring;
#   * a page column is found by its header words, and by the request's fixed column order only
#     when a seven-column table keys its first cell on an ID;
#   * a stated value is graded to the precision the criterion states, 0.005 of an hour, 0.00005 of
#     an hourly rate, half a cent on a dollar total, and its neighbours fail;
#   * the BambooHR tables are discovered by name hint and validated by content, the employee table
#     by its employee numbers, the policy table by its three policy names, the assignment and
#     balance tables by their references into those two, integer id or seed string alike;
#   * it never raises, and details name every table, column list, row and candidate it read, with
#     the reason each was accepted or rejected.
import re

PAGES_COLS = ["id", "path", "hash", "title", "description", "isPrivate", "isPublished",
              "privateNS", "publishStartDate", "publishEndDate", "content", "render", "toc",
              "contentType", "createdAt", "updatedAt", "editorKey", "localeCode", "authorId",
              "creatorId", "extra"]
TRUE_VALUES = ("1", "true", "t", "yes", "y")
SEPS = " -(:,.;/["
ID_RE = r"(?:trt|ctr)-\d{4}"
# the request's column order, the fallback when a header carries no usable words
MEMO_COLS = ["employee id", "name", "department", "tier", "balance", "rate", "liability"]
HINTS = {"employee id": ("employee id", "id"), "name": ("name",), "department": ("department", "dept"),
         "tier": ("tier",), "balance": ("balance",), "rate": ("rate",), "liability": ("liability",)}
POLICY_NAMES = {"pto under 2 years": 80, "pto 2 to 5 years": 120, "pto 5 plus years": 160}
TOL_HOURS, TOL_RATE, TOL_MONEY = 0.005, 0.00005, 0.005


def _text(v):
    return "" if v is None else str(v)


def _norm(s):
    s = _text(s).replace("–", "-").replace("—", "-").replace("−", "-")
    s = re.sub(r"[*_`]+", "", s)
    s = re.sub(r"\s+", " ", s).strip().lower()
    return s


def _clean(raw):
    """Markup out, line structure and table rows kept, so an HTML page reads like markdown."""
    s = _text(raw).replace("\\n", "\n")
    s = re.sub(r"<(?:del|s|strike)\b[^>]*>.*?</(?:del|s|strike)\s*>", " ", s, flags=re.I | re.S)
    s = re.sub(r"~~.*?~~", " ", s, flags=re.S)
    s = re.sub(r"</(?:td|th)\s*>", " | ", s, flags=re.I)
    s = re.sub(r"<tr\b[^>]*>", "\n| ", s, flags=re.I)
    s = re.sub(r"</(?:tr|p|div|li|h[1-6])\s*>|<br\s*/?>", "\n", s, flags=re.I)
    s = re.sub(r"<[^>]+>", " ", s)
    s = s.replace("&nbsp;", " ").replace("&amp;", "&")
    s = re.sub(r"&(?:ndash|mdash|minus);", "-", s)
    s = re.sub(r"[ \t]+", " ", s)
    return "\n".join(l.strip() for l in s.split("\n")).strip()


def _tables(body):
    """Every pipe table on the page as (headers, rows, first_line); separator lines dropped."""
    out, header, rows, first = [], None, [], None
    lines = body.split("\n")
    for n, line in enumerate(lines + ["end"]):
        if not line.strip() and n < len(lines):
            continue
        if line.count("|") < 2:
            if header is not None and rows:
                out.append((header, rows, first))
            header, rows, first = None, [], None
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if all(re.fullmatch(r":?-{2,}:?", c or "--") for c in cells):
            continue
        if header is None:
            header, first = [_norm(c) for c in cells], n
            continue
        if not any(c for c in cells):
            continue
        rows.append(cells)
    return out


def _prose(body):
    return "\n".join(l for l in body.split("\n") if l.count("|") < 2)


def _num(cell):
    """A number out of a cell: commas, a currency sign, a unit word or a trailing note tolerated;
    None where no single number is there."""
    s = _norm(cell).replace(",", "")
    s = re.sub(r"\b(hours?|hrs?|usd)\b", " ", s).replace("$", " ").strip()
    m = re.fullmatch(r"-?\d+(?:\.\d+)?", s)
    if m:
        return float(m.group(0))
    m = re.fullmatch(r"(-?\d+(?:\.\d+)?)\s*(?:\(.*\)|per .*)?", s)
    return float(m.group(1)) if m else None


def _tier(cell):
    c = _norm(cell)
    if c in POLICY_NAMES:
        return POLICY_NAMES[c]
    for name, hours in POLICY_NAMES.items():
        if c.startswith(name):
            return hours
    n = _num(cell)
    return int(n) if n in (80.0, 120.0, 160.0) else None


def _is_id(cell):
    return re.fullmatch(ID_RE, _norm(cell)) is not None


def _is_name(cell):
    """A cell that reads as a person's name: non-empty, no digit, not an ID, not a total word."""
    n = _norm(cell)
    return bool(n) and not re.search(r"\d", n) and not _is_id(n) \
        and not re.search(r"\b(total|totals|subtotal|sum|average|count)\b", n)


def _key_of(row):
    """The whole-cell ID that keys a row, or None. A key is a whole cell, or a whole cell with a
    note in parentheses beside it."""
    for c in row:
        n = _norm(c)
        if re.fullmatch(ID_RE, n) or re.fullmatch(ID_RE + r" \(.*\)", n):
            return n.split(" (")[0].upper()
    return None


def _bool(v):
    return _norm(v) in TRUE_VALUES


class _Page(object):
    def __init__(self, title, body, published, route):
        self.title, self.body, self.published, self.route = title, body, published, route
        self.tables = _tables(body)
        # an employee table is a table carrying at least one keyed row; its unkeyed rows are kept
        # so a total line, a note or an employee row missing its ID can be told apart
        self.emp_tables = [(h, rows, first) for h, rows, first in self.tables if any(_key_of(r) for r in rows)]

    def keyed(self):
        """{ID: (headers, row)} over every employee table; a duplicate key keeps the first."""
        out = {}
        for h, rows, first in self.emp_tables:
            for r in rows:
                k = _key_of(r)
                if k:
                    out.setdefault(k, (h, r))
        return out

    def unkeyed_named(self, notes):
        """The unkeyed rows on the employee tables that carry a name: (headers, row, has a figure).
        With a balance or a liability beside the name it is an employee row missing its ID, and it
        counts and sums as one; without a figure it is a note, which counts for nothing."""
        out = []
        for h, rows, first in self.emp_tables:
            ni = self.col(h, "name", notes)
            for r in rows:
                if _key_of(r):
                    continue
                name = r[ni] if ni is not None and ni < len(r) else ""
                if not _is_name(name):
                    continue
                figs = [_num(r[i]) for i in (self.col(h, "balance", notes), self.col(h, "liability", notes))
                        if i is not None and i < len(r)]
                out.append((h, r, any(f is not None for f in figs)))
        return out

    def employee_rows(self, notes):
        """Every employee row: the keyed rows and the unkeyed rows that carry a name and a figure."""
        return list(self.keyed().values()) + [(h, r) for h, r, fig in self.unkeyed_named(notes) if fig]

    def col(self, headers, want, notes):
        """The index of the wanted column on this header, by hint words first, by the request's
        order when the header carries no usable words and the table has seven columns."""
        for hint in HINTS[want]:
            for i, h in enumerate(headers):
                if hint in h and not (want == "employee id" and hint == "id" and "policy" in h):
                    return i
        if len(headers) == len(MEMO_COLS):
            notes.append("column %r not in the header %r; taking the request's position %d"
                         % (want, headers, MEMO_COLS.index(want)))
            return MEMO_COLS.index(want)
        return None


def _pages_table(ctx, notes):
    if ctx.has_table("pages"):
        return "pages"
    for name in ctx.list_tables():
        low = name.lower()
        if "page" in low and not any(x in low for x in ("history", "tree", "link", "tag", "meta")):
            notes.append("no table named pages; using %s" % name)
            return name
    return None


def _load_pages(ctx, title, notes):
    """Every row of the pages table whose title matches, with its content and published flag
    resolved by content, or by the documented Wiki.js layout when the row's shape validates."""
    name = _pages_table(ctx, notes)
    if not name:
        notes.append("no pages table in this snapshot: %r" % ctx.list_tables())
        return []
    cols = list(ctx.table_columns(name))
    rows = [list(r) for r in ctx.query_db("SELECT * FROM %s" % name)]
    real = "title" in cols and "content" in cols
    notes.append("table %s: %d columns %r, %d rows, %s column names"
                 % (name, len(cols), cols, len(rows), "real" if real else "placeholder"))
    found = []
    for n, r in enumerate(rows):
        hits = [i for i, v in enumerate(r) if _norm(v) == _norm(title)]
        if not hits:
            continue
        if real:
            body = _clean(r[cols.index("content")])
            pub = _bool(r[cols.index("isPublished")]) if "isPublished" in cols else None
            route = "real names"
        elif len(r) == len(PAGES_COLS) and 3 in hits:
            body = _clean(r[10])
            pub = _bool(r[6])
            route = "documented layout, validated on the title at index 3 and %d columns" % len(r)
        else:
            cand = [_clean(v) for v in r if isinstance(v, str)]
            cand = [c for c in cand if ("|" in c or "#" in c) and len(c) > 40]
            body = max(cand, key=len) if cand else ""
            pub = None
            route = "content resolved as the longest table-bearing cell; published flag unknown"
        notes.append("page row %d matches the title via %s; %d chars of content, published=%r"
                     % (n, route, len(body), pub))
        found.append(_Page(title, body, pub, route))
    if not found:
        notes.append("no row of %s carries the title %r" % (name, title))
    return found


def _money_figures(text):
    return [float(m.replace(",", "")) for m in re.findall(r"\$\s?(\d{1,3}(?:,\d{3})*\.\d{2}|\d+\.\d{2})\b", text)]


def _hour_figures(text):
    return [float(m.replace(",", "")) for m in re.findall(r"(?<![\d.$])(\d{1,3}(?:,\d{3})*\.\d{2}|\d+\.\d{2})(?![\d.])", text)]


def _cell(page, key, want, notes):
    """(cell, headers) for the keyed row's wanted column, or (None, reason)."""
    keyed = page.keyed()
    if key not in keyed:
        return None, "no employee row keyed %s on the page" % key
    h, r = keyed[key]
    i = page.col(h, want, notes)
    if i is None or i >= len(r):
        return None, "no %r column on the table keyed %s, header %r" % (want, key, h)
    return r[i], h


def _run_page(kind, page, notes, metrics):
    S = SPEC
    keyed = page.keyed()
    metrics["keyed_rows"] = len(keyed)
    if kind == "exists":
        if page.published is None:
            return False, "the published flag could not be read, so publication is not shown"
        return page.published, "published=%r" % page.published
    if kind == "present":
        want = {k.upper() for k in S["expected_ids"]}
        missing = sorted(want - set(keyed))
        notes.append("keyed rows %d, expected %d present, missing %d" % (len(keyed), len(want), len(missing)))
        if missing:
            return False, "%d expected rows missing (%s)" % (len(missing), ", ".join(missing[:5]))
        return True, "all %d current employees present" % len(want)
    if kind == "idset":
        want = {k.upper() for k in S["expected_ids"]}
        seen = set(keyed)
        missing, extra = sorted(want - seen), sorted(seen - want)
        notes.append("keyed rows %d, expected %d, missing %d, extra %d" % (len(seen), len(want), len(missing), len(extra)))
        if missing or extra:
            return False, "%d expected rows missing (%s) and %d rows outside the population (%s)" % (
                len(missing), ", ".join(missing[:5]) or "none", len(extra), ", ".join(extra[:5]) or "none")
        return True, "the %d current employees and no other row" % len(want)
    if kind in ("absent", "no_contractor"):
        if len(keyed) < S["min_rows"]:
            return False, "%d keyed rows on the page, under the %d a schedule carries; absence from a thin table shows nothing" % (len(keyed), S["min_rows"])
        if kind == "absent":
            hit = [k for k in keyed if k in {x.upper() for x in S["keys"]}]
        else:
            hit = [k for k in keyed if k.startswith("CTR-")]
        if hit:
            return False, "%s sits on an employee table" % ", ".join(hit)
        return True, "absent from %d keyed rows" % len(keyed)
    if kind in ("balance", "rate", "tier"):
        want_col = {"balance": "balance", "rate": "rate", "tier": "tier"}[kind]
        cell, h = _cell(page, S["key"], want_col, notes)
        if cell is None:
            return False, h
        if kind == "tier":
            got = _tier(cell)
            notes.append("row %s: tier cell %r reads %r, expected %d" % (S["key"], cell, got, S["expected"]))
            return got == S["expected"], "tier %r" % got
        got = _num(cell)
        tol = TOL_HOURS if kind == "balance" else TOL_RATE
        oks = [abs(got - x) <= tol for x in S["expected"]] if got is not None else []
        notes.append("row %s: %s cell %r reads %r, expected one of %r within %s" % (S["key"], want_col, cell, got, S["expected"], tol))
        return any(oks), "%s %r" % (want_col, got)
    if kind == "total":
        prose = _prose(page.body)
        stated = _money_figures(prose)
        for h, rows, first in page.tables:
            for r in rows:
                if not _key_of(r):
                    stated += [x for c in r for x in _money_figures(c)]
        li = None
        row_sum = 0.0
        for k, (h, r) in keyed.items():
            i = page.col(h, "liability", notes) if li is None else li
            li = i
            v = _num(r[i]) if i is not None and i < len(r) else None
            row_sum += v or 0.0
        row_sum = round(row_sum, 2)
        metrics["stated_totals"] = len(stated)
        metrics["row_sum"] = row_sum
        hits = [x for x in stated if any(abs(x - t) <= TOL_MONEY for t in S["expected"])]
        notes.append("dollar figures outside employee rows: %r; employee rows sum to %.2f; expected one of %r" % (stated[:12], row_sum, S["expected"]))
        if hits:
            return True, "stated total %.2f" % hits[0]
        if stated:
            return False, "the page states %r and none is the total" % (stated[:6],)
        if any(abs(row_sum - t) <= TOL_MONEY for t in S["expected"]):
            return True, "no total is stated and the rows sum to %.2f" % row_sum
        return False, "no total equal to %r stated or summed" % (S["expected"],)
    if kind == "format":
        if not keyed:
            return False, "no employee rows"
        bad = []
        pats = {"balance": r"-?[\d,]+\.\d{2}(?:\s*(?:hours|hrs))?", "rate": r"\$?\s?[\d,]+\.\d{4}",
                "liability": r"-?\$?\s?[\d,]+\.\d{2}"}
        fields = [S["field"]] if S.get("field") else list(pats)
        for k, (h, r) in keyed.items():
            for want in fields:
                pat = pats[want]
                i = page.col(h, want, notes)
                cell = r[i] if i is not None and i < len(r) else ""
                if not re.fullmatch(pat, _norm(cell)):
                    bad.append((k, want, cell))
        metrics["bad_cells"] = len(bad)
        if bad:
            return False, "%d cells outside the form, first %r" % (len(bad), bad[0])
        return True, "%d rows in form" % len(keyed)
    if kind == "reconcile":
        if not keyed:
            return False, "no employee rows"
        emp = page.employee_rows(notes)
        total = 0.0
        for h, r in emp:
            i = page.col(h, "liability", notes)
            total += (_num(r[i]) if i is not None and i < len(r) else None) or 0.0
        total = round(total, 2)
        emp_ids = {id(r) for h, r in emp}
        stated = _money_figures(_prose(page.body)) + [x for h, rows, f in page.tables for r in rows if id(r) not in emp_ids for c in r for x in _money_figures(c)]
        metrics["row_sum"] = total
        metrics["employee_rows"] = len(emp)
        notes.append("rows sum to %.2f; stated dollar figures %r" % (total, stated[:8]))
        if not stated:
            return False, "no total is stated"
        if any(abs(x - total) <= 0.01 for x in stated):
            return True, "a stated total equals the sum of the rows, %.2f" % total
        return False, "no stated total equals the sum of the rows, %.2f" % total
    if kind == "id_rows":
        if not page.emp_tables:
            return False, "no employee table"
        bad = [r[0] if r else "" for h, r, fig in page.unkeyed_named(notes)]
        metrics["rows_without_id"] = len(bad)
        if bad:
            return False, "%d rows carry a name and no employee ID, first %r" % (len(bad), bad[0])
        return True, "an employee ID on every one of %d rows" % len(keyed)
    if kind == "dates":
        body = page.body
        iso = re.findall(r"\b\d{4}-\d{2}-\d{2}\b", body)
        spelled = re.findall(r"\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?\s+\d{1,2}(?!\d)"
                             r"(?:st|nd|rd|th)?,?\s+\d{4}", body, flags=re.I)
        dmy = re.findall(r"\b\d{1,2}\.\d{1,2}\.\d{4}\b", body)
        us = re.findall(r"\b\d{2}/\d{2}/\d{4}\b", body)
        metrics["us_dates"] = len(us)
        if iso or spelled or dmy:
            return False, "dates outside MM/DD/YYYY: %r" % (iso + spelled + dmy)[:3]
        if not us:
            return False, "no MM/DD/YYYY date on the page"
        return True, "%d dates, all MM/DD/YYYY" % len(us)
    if kind == "summary":
        if not keyed:
            return False, "no employee rows"
        emp = page.employee_rows(notes)
        prose = _norm(_prose(page.body))
        count_ok = re.search(r"(?<!\d)%d(?!\d)" % len(emp), prose) is not None
        hours = round(sum(_num(r[page.col(h, "balance", notes)] or "") or 0.0 for h, r in emp), 2)
        dollars = round(sum(_num(r[page.col(h, "liability", notes)] or "") or 0.0 for h, r in emp), 2)
        hours_ok = any(abs(x - hours) <= 0.01 for x in _hour_figures(prose))
        money_ok = bool(_money_figures(prose))
        notes.append("summary: count %d stated=%s, hours %.2f stated=%s, a dollar figure stated=%s (rows sum to %.2f)"
                     % (len(emp), count_ok, hours, hours_ok, money_ok, dollars))
        if count_ok and hours_ok and money_ok:
            return True, "the count, the total hours and the total liability are stated"
        return False, "the summary lacks %s" % ", ".join(x for x, ok in (("the count", count_ok), ("the total hours", hours_ok), ("the total liability", money_ok)) if not ok)
    if kind == "columns":
        if not keyed:
            return False, "no employee rows"
        blank = []
        wants = [S["field"]] if S.get("field") else ["name", "department", "tier"]
        for k, (h, r) in keyed.items():
            for want in wants:
                i = page.col(h, want, notes)
                cell = r[i] if i is not None and i < len(r) else ""
                if not _norm(cell) or _is_id(cell) or (want == "tier" and _tier(cell) is None):
                    blank.append((k, want, cell))
        metrics["blank_cells"] = len(blank)
        if blank:
            return False, "%d rows lack a name, a department or a tier, first %r" % (len(blank), blank[0])
        return True, "a name, a department and a tier on all %d rows" % len(keyed)
    if kind == "layout":
        if not page.emp_tables:
            return False, "no employee table"
        if len(page.emp_tables) > 1:
            return False, "%d tables carry employee rows; the request asks for one" % len(page.emp_tables)
        first = page.emp_tables[0][2]
        before = "\n".join(page.body.split("\n")[:first])
        before_prose = _norm(_prose(before))
        count_ok = re.search(r"(?<!\d)%d(?!\d)" % len(page.employee_rows(notes)), before_prose) is not None
        money_ok = bool(_money_figures(before_prose))
        notes.append("one employee table at line %d; before it the count is %s and a dollar figure is %s"
                     % (first, "stated" if count_ok else "absent", "stated" if money_ok else "absent"))
        if count_ok and money_ok:
            return True, "the summary sits above the one employee table"
        return False, "no summary with the count and a dollar figure above the table"
    return False, "unknown check kind %r" % kind


# ---------------------------------------------------------------- BambooHR
def _load(ctx, name):
    cols = list(ctx.table_columns(name))
    rows = [list(r) for r in ctx.query_db("SELECT * FROM %s" % name)]
    return cols, rows


def _int(v):
    try:
        f = float(str(v).strip())
        return int(f) if f == int(f) else None
    except (TypeError, ValueError):
        return None


class _Bamboo(object):
    """The BambooHR tables a grading snapshot holds, resolved by name hint and content. Employee
    numbers, policy names and every reference into them are resolved to the business key, so a
    row keyed on the app's integer id and a row keyed on the seed's string read the same."""

    def __init__(self, ctx, notes):
        self.notes = notes
        self.emp_by_num, self.emp_ids = {}, {}
        self.pol_by_id, self.pol_names = {}, set()
        self.assign, self.balances = {}, {}
        self.ok = False
        names = list(ctx.list_tables())
        notes.append("tables in the snapshot: %r" % names)
        cache = {n: _load(ctx, n) for n in names if "page" not in n.lower()}
        for n, (cols, rows) in cache.items():
            notes.append("table %s: %d columns, %d rows" % (n, len(cols), len(rows)))
        emp = self._employee_table(cache)
        pol = self._policy_table(cache)
        if not emp or not pol:
            notes.append("employee table %r, policy table %r; cannot resolve BambooHR" % (emp, pol))
            return
        self._assignments(cache, emp, pol)
        self._balances(cache, emp, pol)
        self.ok = True

    def _employee_table(self, cache):
        """The table with 40 or more distinct employee numbers in one column, each once, and an
        email column beside them: the assignment and balance tables carry the numbers too when the
        loader keeps the seed's strings, and a count won by one row is no way to tell them apart."""
        best = None
        for n, (cols, rows) in cache.items():
            for ci in range(len(cols)):
                nums = [_norm(r[ci]) for r in rows if ci < len(r) and _is_id(r[ci])]
                if len(set(nums)) < 40 or len(set(nums)) != len(nums):
                    continue
                emails = max((sum(1 for r in rows if cj < len(r) and "@" in _text(r[cj])) for cj in range(len(cols))), default=0)
                score = (1 if emails >= len(rows) // 2 else 0, len(set(nums)))
                if best is None or score > best[4]:
                    best = (n, ci, rows, len(set(nums)), score)
        if not best:
            self.notes.append("no table carries 40 or more distinct employee numbers")
            return None
        n, ci, rows, k, score = best
        self.notes.append("employee table chosen with%s an email column" % ("" if score[0] else "out"))
        cols = cache[n][0]
        idc = self._id_column(rows, exclude=(ci,))
        for r in rows:
            num = _norm(r[ci]).upper() if ci < len(r) else ""
            if not _is_id(num):
                continue
            self.emp_by_num[num] = r
            if idc is not None and idc < len(r) and _int(r[idc]) is not None:
                self.emp_ids[str(_int(r[idc]))] = num
        self.notes.append("employee table %s: numbers in column %d (%d distinct), integer id in column %r"
                          % (n, ci, k, idc))
        return n

    def _id_column(self, rows, exclude=()):
        """The first column whose values are distinct integers on every row: the app's own id."""
        if not rows:
            return None
        for ci in range(len(rows[0])):
            if ci in exclude:
                continue
            vals = [_int(r[ci]) for r in rows if ci < len(r)]
            if all(v is not None for v in vals) and len(set(vals)) == len(vals):
                return ci
        return None

    def _policy_table(self, cache):
        """The table where a column carries the three policy names once each: the assignment and
        balance tables carry the names too when the loader keeps the seed's strings, many times."""
        for n, (cols, rows) in cache.items():
            for ci in range(len(cols)):
                vals = [_norm(r[ci]) for r in rows if ci < len(r)]
                found = set(vals) & set(POLICY_NAMES)
                if len(found) == 3 and len(vals) == len(set(vals)) and all(v in POLICY_NAMES or not v for v in vals):
                    idc = self._id_column(rows, exclude=(ci,))
                    for r in rows:
                        name = _norm(r[ci]) if ci < len(r) else ""
                        if name in POLICY_NAMES:
                            self.pol_names.add(name)
                            if idc is not None and idc < len(r) and _int(r[idc]) is not None:
                                self.pol_by_id[str(_int(r[idc]))] = name
                    self.notes.append("policy table %s: names in column %d, integer id in column %r" % (n, ci, idc))
                    return n
        self.notes.append("no table carries the three policy names")
        return None

    def _emp_ref(self, v):
        s = _norm(v).upper()
        if _is_id(s):
            return s
        i = _int(v)
        return self.emp_ids.get(str(i)) if i is not None else None

    def _pol_ref(self, v):
        s = _norm(v)
        if s in POLICY_NAMES:
            return s
        i = _int(v)
        return self.pol_by_id.get(str(i)) if i is not None else None

    def _ref_columns(self, rows):
        """(employee column, policy column) on a table: the column resolving to 40 or more distinct
        employee numbers, and the column resolving to the most distinct policy names on at least
        half the rows. The table's own id column is a run of small integers that resolves to
        employee numbers by coincidence, so it is skipped unless nothing else resolves."""
        if not rows:
            return None, None
        own = self._id_column(rows)
        ec, pc = None, None
        order = [ci for ci in range(len(rows[0])) if ci != own] + ([own] if own is not None else [])
        for ci in order:
            refs = {self._emp_ref(r[ci]) for r in rows if ci < len(r)} - {None}
            if len(refs) >= 40:
                ec = ci
                break
        best = None
        for ci in range(len(rows[0])):
            if ci in (ec, own):
                continue
            names = [self._pol_ref(r[ci]) for r in rows if ci < len(r)]
            hits = sum(1 for x in names if x is not None)
            if hits >= max(1, len(rows) // 2) and (best is None or len(set(names) - {None}) > best[0]):
                best = (len(set(names) - {None}), ci)
        pc = best[1] if best else None
        return ec, pc

    def _date_columns(self, rows):
        out = []
        for ci in range(len(rows[0]) if rows else 0):
            hits = sum(1 for r in rows if ci < len(r) and re.fullmatch(r"\d{4}-\d{2}-\d{2}.*", _text(r[ci]).strip()))
            if hits >= max(1, len(rows) // 2):
                out.append(ci)
        return out

    def _year_column(self, rows):
        for ci in range(len(rows[0]) if rows else 0):
            vals = [_int(r[ci]) for r in rows if ci < len(r)]
            if vals and all(v is not None and 2000 <= v <= 2100 for v in vals):
                return ci
        return None

    def _status_column(self, rows):
        for ci in range(len(rows[0]) if rows else 0):
            vals = {_norm(r[ci]) for r in rows if ci < len(r)}
            if vals and vals <= {"approved", "pending", "denied", "cancelled", "canceled", "requested", "superceded", "superseded"}:
                return ci
        return None

    def _assignments(self, cache, emp, pol):
        cands = []
        for n, (cols, rows) in cache.items():
            if n in (emp, pol) or not rows:
                continue
            ec, pc = self._ref_columns(rows)
            if ec is None or pc is None:
                continue
            if self._year_column(rows) is not None or self._status_column(rows) is not None:
                continue
            dates = self._date_columns(rows)
            cands.append((0 if "polic" in n.lower() or "assign" in n.lower() else 1, n, rows, ec, pc, dates))
        if not cands:
            self.notes.append("no table resolves as the employee-policy assignments")
            return
        cands.sort(key=lambda c: c[0])
        _, n, rows, ec, pc, dates = cands[0]
        eff = dates[0] if dates else None
        end = dates[1] if len(dates) > 1 else None
        self.notes.append("assignment table %s: employee column %d, policy column %d, effective date column %r, end date column %r, %d rows"
                          % (n, ec, pc, eff, end, len(rows)))
        per = {}
        for r in rows:
            e, p = self._emp_ref(r[ec]) if ec < len(r) else None, self._pol_ref(r[pc]) if pc < len(r) else None
            if e is None or p is None:
                continue
            ended = _text(r[end]).strip() if end is not None and end < len(r) else ""
            when = _text(r[eff]).strip() if eff is not None and eff < len(r) else ""
            per.setdefault(e, []).append((0 if not ended or ended[:10] > "2026-08-31" else 1, when, p))
        for e, lst in per.items():
            lst.sort(key=lambda t: (t[0], "" if t[0] else t[1]))
            open_ = [t for t in lst if t[0] == 0]
            pick = max(open_, key=lambda t: t[1]) if open_ else max(lst, key=lambda t: t[1])
            self.assign[e] = pick[2]

    def _balances(self, cache, emp, pol):
        cands = []
        for n, (cols, rows) in cache.items():
            if n in (emp, pol) or not rows:
                continue
            ec, pc = self._ref_columns(rows)
            if ec is None or self._status_column(rows) is not None:
                continue
            yc = self._year_column(rows)
            if yc is None and "balance" not in n.lower():
                continue
            cands.append((0 if "balance" in n.lower() else 1, n, rows, ec, pc, yc))
        if not cands:
            self.notes.append("no table resolves as the time-off balances")
            return
        cands.sort(key=lambda c: c[0])
        _, n, rows, ec, pc, yc = cands[0]
        # the balance column: numeric on every row, not the year, the ids or the references, and
        # the first such column, which is where the seed and the documented layout put it
        skip = {ec, pc, yc, self._id_column(rows, exclude=())}
        bc = None
        for ci in range(len(rows[0])):
            if ci in skip:
                continue
            vals = [_num(r[ci]) for r in rows if ci < len(r)]
            if all(v is not None for v in vals):
                bc = ci
                break
        self.notes.append("balance table %s: employee column %d, policy column %r, year column %r, balance column %r, %d rows"
                          % (n, ec, pc, yc, bc, len(rows)))
        if bc is None:
            return
        for r in rows:
            e = self._emp_ref(r[ec]) if ec < len(r) else None
            if e is None:
                continue
            year = _int(r[yc]) if yc is not None and yc < len(r) else None
            p = self._pol_ref(r[pc]) if pc is not None and pc < len(r) else None
            self.balances.setdefault(e, []).append((year, p, _num(r[bc])))

    def balance(self, num):
        """The employee's balance: the 2026 row on the current policy, or the one 2026 row, or the
        one row; None with a reason otherwise."""
        rows = self.balances.get(num, [])
        if not rows:
            return None, "no balance row for %s" % num
        cur = [r for r in rows if r[0] in (None, 2026)]
        if len(cur) > 1 and self.assign.get(num):
            cur = [r for r in cur if r[1] in (None, self.assign[num])] or cur
        if len(cur) != 1:
            return None, "%d balance rows for %s in 2026, %r; the balance is ambiguous" % (len(cur), num, cur)
        return cur[0][2], "balance %r on policy %r" % (cur[0][2], cur[0][1])


def _run_bamboo(kind, bam, notes, metrics):
    S = SPEC
    if not bam.ok:
        return False, "the BambooHR tables could not be resolved"
    if kind == "policies":
        bad, seen = [], 0
        for num, want in S["expected"].items():
            got = bam.assign.get(num.upper())
            seen += 1
            if got != _norm(want):
                bad.append((num, got, want))
        metrics["employees"] = seen
        metrics["wrong"] = len(bad)
        notes.append("policies checked on %d employees, %d differ: %r" % (seen, len(bad), bad[:8]))
        return not bad, "%d of %d policies match the schedule" % (seen - len(bad), seen)
    if kind == "balances":
        bad = []
        for num, wants in S["expected"].items():
            got, why = bam.balance(num.upper())
            if got is None or not any(abs(got - w) <= TOL_HOURS for w in wants):
                bad.append((num, got, wants, why))
        metrics["employees"] = len(S["expected"])
        metrics["wrong"] = len(bad)
        notes.append("balances checked on %d employees, %d differ: %r" % (len(S["expected"]), len(bad), bad[:6]))
        return not bad, "%d of %d balances match the schedule" % (len(S["expected"]) - len(bad), len(S["expected"]))
    if kind == "policy":
        num = S["key"].upper()
        if num not in bam.emp_by_num:
            return False, "no employee row carries %s" % num
        got = bam.assign.get(num)
        notes.append("row %s: current policy %r, expected %r" % (num, got, S["expected"]))
        return got == _norm(S["expected"]), "policy %r" % got
    if kind == "balance_row":
        num = S["key"].upper()
        if num not in bam.emp_by_num:
            return False, "no employee row carries %s" % num
        got, why = bam.balance(num)
        notes.append("row %s: %s" % (num, why))
        if got is None:
            return False, why
        ok = any(abs(got - w) <= TOL_HOURS for w in S["expected"])
        return ok, "balance %r against %r" % (got, S["expected"])
    return False, "unknown check kind %r" % kind


def check(ctx):
    notes, metrics = [], {}

    def fail(reason):
        return {"passed": False, "details": "\n".join(notes + ["", "FAILED - " + reason]), "metrics": metrics}

    try:
        if SPEC["target"] == "bamboohr":
            bam = _Bamboo(ctx, notes)
            ok, why = _run_bamboo(SPEC["kind"], bam, notes, metrics)
            if ok:
                return {"passed": True, "metrics": metrics, "details": "\n".join(notes + ["", "PASSED - " + why])}
            return fail(why)
        pages = _load_pages(ctx, SPEC["page"], notes)
        if not pages:
            return fail("no page titled %r" % SPEC["page"])
        verdicts = []
        for p in pages:
            ok, why = _run_page(SPEC["kind"], p, notes, metrics)
            notes.append("page %r: %s - %s" % (SPEC["page"], "ok" if ok else "NO", why))
            verdicts.append(ok)
        # every row carrying the title has to satisfy: a wrong duplicate leaves the wiki wrong
        if verdicts and all(verdicts):
            return {"passed": True, "metrics": metrics,
                    "details": "\n".join(notes + ["", "PASSED - %d page row(s) satisfy" % len(verdicts)])}
        return fail("%d of %d page rows fail" % (verdicts.count(False), len(verdicts)))
    except Exception as exc:
        notes.append("unexpected error: %s: %s" % (type(exc).__name__, str(exc)[:300]))
        return fail("the check could not complete; see the error above")
