# Row 33 of the Approved Hiring and Staffed Role Views rubric - generated by build/build_package_artifacts.py, never edited here.
# Criterion: States, on the staffed role page, that BambooHR carries 57 active records.
# Target app: wiki_js, table pages, check kind summary
SPEC = {'criterion': 'States, on the staffed role page, that BambooHR carries 57 active records.',
 'kind': 'summary',
 'pages': ['Staffed Role View - August 2026'],
 'prose_only': True,
 'regex': '\\b57\\b[^.\\n]{0,80}(bamboohr|active record|hris)|(bamboohr|active '
          'record|hris)[^.\\n]{0,80}\\b57\\b'}

# ---- verifier engine. The builder prepends `SPEC = {...}` to this file to make one standalone
# ---- check(ctx) per rubric row, written to qc/verifiers/. Edit the engine here, never a row file.
#
# What keeps it honest, in the order the app-db-verifier skill lists them:
#   * it reads the wiki database and nothing else - no files, no trajectory, no final answer;
#   * it never names a column in SQL, and resolves the pages table's columns by content, falling
#     back to the documented Wiki.js column order only when the row's shape validates;
#   * a page is found by its TITLE on a whole-field match, dashes and case normalised;
#   * a table row is found by a WHOLE-CELL match on its key, never a substring;
#   * a status cell must carry the asked value as its leading token, so "Not approved" never
#     satisfies "Approved" and "Approved (conditional)" never satisfies "Not approved";
#   * a count is a count of distinct key cells on the right tables, never a substring tally;
#   * it never raises, and its details name every table, column list, page row and table row it
#     read, with the reason each candidate was accepted or rejected.
import re

PAGES_COLS = ["id", "path", "hash", "title", "description", "isPrivate", "isPublished",
              "privateNS", "publishStartDate", "publishEndDate", "content", "render", "toc",
              "contentType", "createdAt", "updatedAt", "editorKey", "localeCode", "authorId",
              "creatorId", "extra"]
TRUE_VALUES = ("1", "true", "t", "yes", "y")
NONE_VALUES = ("", "none", "-", "n/a", "na", "no", "no open requisition", "not applicable")
SEPS = " -(:,.;/["


def _text(v):
    return "" if v is None else str(v)


def _norm(s):
    s = _text(s).replace("\u2013", "-").replace("\u2014", "-").replace("\u2212", "-")
    s = re.sub(r"[*_`]+", "", s)
    s = re.sub(r"\s+", " ", s).strip().lower()
    return s


def _clean(raw):
    """Markup out, line structure and table rows kept, so an HTML page reads like markdown."""
    s = _text(raw).replace("\\n", "\n")
    s = re.sub(r"<(?:del|s|strike)\b[^>]*>.*?</(?:del|s|strike)\s*>", " ", s, flags=re.I | re.S)
    s = re.sub(r"~~.*?~~", " ", s, flags=re.S)
    s = re.sub(r"</(?:td|th)\s*>", " | ", s, flags=re.I)
    s = re.sub(r"<tr\b[^>]*>", "\n| ", s, flags=re.I)
    s = re.sub(r"</(?:tr|p|div|li|h[1-6])\s*>|<br\s*/?>", "\n", s, flags=re.I)
    s = re.sub(r"<[^>]+>", " ", s)
    s = s.replace("&nbsp;", " ").replace("&amp;", "&")
    s = re.sub(r"&(?:ndash|mdash|minus);", "-", s)
    s = re.sub(r"[ \t]+", " ", s)
    return "\n".join(l.strip() for l in s.split("\n")).strip()


def _tables(body):
    """Every pipe table on the page as (headers, rows); separator lines dropped."""
    out, header, rows = [], None, []
    lines = body.split("\n")
    for n, line in enumerate(lines + ["end"]):
        if not line.strip() and n < len(lines):
            continue          # a blank line neither ends a table nor adds to it (HTML rows)
        if line.count("|") < 2:
            if header is not None and rows:
                out.append((header, rows))
            header, rows = None, []
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if all(re.fullmatch(r":?-{2,}:?", c or "--") for c in cells):
            continue
        if header is None:
            header = [_norm(c) for c in cells]
            continue
        if not any(c for c in cells):
            continue
        rows.append(cells)
    return out


def _prose(body):
    """The page with its table lines removed, which is where a summary lives."""
    return "\n".join(l for l in body.split("\n") if l.count("|") < 2)


def _col(headers, hint):
    """The index of the header carrying every word of the hint, or None."""
    words = _norm(hint).split()
    for i, h in enumerate(headers):
        if all(w in h for w in words):
            return i
    return None


def _leading(cell, wanted):
    """The cell carries `wanted` as its leading value: equal, or followed by a separator."""
    c, w = _norm(cell), _norm(wanted)
    return c == w or (c.startswith(w) and c[len(w):len(w) + 1] in SEPS)


def _key_match(cell, keys):
    """The cell is the key, or the key with an identifier in parentheses beside it, as in
    Kwame Adjei (ATS-4471): a run that prints the person's ID beside the name has still keyed
    the row on the name. Anything else beside the key is another key."""
    c = _norm(cell)
    return any(c == _norm(k) or (c.startswith(_norm(k) + " (") and c.endswith(")"))
               for k in keys)


def _bool(v):
    return _norm(v) in TRUE_VALUES


class _Page(object):
    def __init__(self, title, body, published, route):
        self.title, self.body, self.published, self.route = title, body, published, route
        self.tables = _tables(body)


def _pages_table(ctx, notes):
    if ctx.has_table("pages"):
        return "pages"
    for name in ctx.list_tables():
        low = name.lower()
        if "page" in low and not any(x in low for x in ("history", "tree", "link", "tag", "meta")):
            notes.append("no table named pages; using %s" % name)
            return name
    return None


def _load_pages(ctx, title, notes):
    """Every row of the pages table whose title matches, with its content and published flag
    resolved by content, or by the documented Wiki.js layout when the row's shape validates."""
    name = _pages_table(ctx, notes)
    if not name:
        notes.append("no pages table in this snapshot: %r" % ctx.list_tables())
        return []
    cols = list(ctx.table_columns(name))
    rows = [list(r) for r in ctx.query_db("SELECT * FROM %s" % name)]
    real = "title" in cols and "content" in cols
    notes.append("table %s: %d columns %r, %d rows, %s column names"
                 % (name, len(cols), cols, len(rows), "real" if real else "placeholder"))
    found = []
    for n, r in enumerate(rows):
        hits = [i for i, v in enumerate(r) if _norm(v) == _norm(title)]
        if not hits:
            continue
        if real:
            body = _clean(r[cols.index("content")])
            pub = _bool(r[cols.index("isPublished")]) if "isPublished" in cols else None
            route = "real names"
        elif len(r) == len(PAGES_COLS) and 3 in hits:
            body = _clean(r[10])
            pub = _bool(r[6])
            route = "documented layout, validated on the title at index 3 and %d columns" % len(r)
        else:
            cand = [_clean(v) for v in r if isinstance(v, str)]
            cand = [c for c in cand if ("|" in c or "#" in c) and len(c) > 40]
            body = max(cand, key=len) if cand else ""
            pub = None
            route = "content resolved as the longest table-bearing cell; published flag unknown"
        notes.append("page row %d matches the title via %s; %d chars of content, published=%r"
                     % (n, route, len(body), pub))
        found.append(_Page(title, body, pub, route))
    if not found:
        notes.append("no row of %s carries the title %r" % (name, title))
    return found


def _staffed(tables):
    """The staffed-role tables: the ones carrying an open-requisition column."""
    return [(h, rows) for h, rows in tables if _col(h, "open requisition") is not None]


def _keyed_rows(tables, keys, column_hint=None):
    """(headers, row) for every table row whose any cell whole-matches a key, on tables that
    carry the hinted column when a hint is given."""
    out = []
    for h, rows in tables:
        if column_hint and _col(h, column_hint) is None:
            continue
        for r in rows:
            if any(_key_match(c, keys) for c in r):
                out.append((h, r))
    return out


def _run(kind, page, notes, metrics):
    """One page against one spec. Returns (ok, reason)."""
    S = SPEC
    if kind == "exists":
        if page.published is None:
            return False, "the published flag could not be read, so publication is not shown"
        return page.published, "published=%r" % page.published
    if kind in ("cell", "cells"):
        keys = S["keys"]
        want_all = []
        for key in keys:
            hits = _keyed_rows(page.tables, [key] + list(S.get("aliases", {}).get(key, [])),
                               S["column"])
            if not hits:
                notes.append("no table row keyed %r on a table with a %r column" % (key, S["column"]))
                want_all.append(False)
                continue
            for h, r in hits:
                i = _col(h, S["column"])
                cell = r[i] if i < len(r) else ""
                contains = S.get("contains") or (S.get("contains_by_key") or {}).get(key)
                if contains:
                    ok = any(re.search(r"(?<![a-z0-9])%s(?![a-z0-9])" % re.escape(_norm(x)),
                                       _norm(cell)) for x in contains)
                elif S.get("date"):
                    ok = S["date"] in _text(cell)
                else:
                    ok = any(_leading(cell, x) for x in S["expected"])
                notes.append("row %r: %s = %r -> %s" % (key, S["column"], cell, "ok" if ok else "no"))
                want_all.append(ok)
        metrics["rows"] = len(want_all)
        return all(want_all) and bool(want_all), "%d of %d keyed cells satisfy" % (
            sum(want_all), len(want_all))
    if kind == "count":
        tables = _staffed(page.tables)
        if not tables:
            return False, "no table carries an open requisition column"
        seen = {}
        for h, rows in tables:
            fi = _col(h, S["filter_column"]) if S.get("filter_column") else None
            for r in rows:
                key = next((c for c in r if re.fullmatch(S["key_re"], _norm(c))), None)
                if key is None:
                    continue
                if fi is not None:
                    cell = r[fi] if fi < len(r) else ""
                    if S.get("filter_re"):
                        if not re.search(S["filter_re"], _norm(cell)):
                            continue
                    elif S.get("filter_none"):
                        if _norm(cell) not in NONE_VALUES:
                            continue
                    elif not _leading(cell, S["filter_value"]):
                        continue
                seen[_norm(key)] = True
        n = len(seen)
        metrics["counted"] = n
        notes.append("distinct keys counted: %d, expected %d" % (n, S["expected"]))
        if n != S["expected"]:
            return False, "counted %d rows, expected %d" % (n, S["expected"])
        if S.get("own_table"):
            for h, rows in tables:
                fi = _col(h, S["filter_column"])
                nones = [r for r in rows if fi is not None and fi < len(r)
                         and _norm(r[fi]) in NONE_VALUES]
                reqs = [r for r in rows if fi is not None and fi < len(r)
                        and re.search(r"req-\d{4}-\d{3}", _norm(r[fi]))]
                if nones and reqs:
                    return False, "a table mixes %d no-requisition rows with %d requisition rows" % (
                        len(nones), len(reqs))
        if S.get("summary_re"):
            prose = _norm(_prose(page.body))
            if not re.search(S["summary_re"], prose):
                return False, "the table count is right but the summary does not state it"
            notes.append("summary states the figure")
        if S.get("summary_figure_re"):
            prose = _norm(_prose(page.body))
            for m in re.finditer(S["summary_figure_re"], prose):
                fig = int(m.group("n"))
                if fig != S["expected"]:
                    return False, "the summary states %d where the tables carry %d" % (fig, n)
        return True, "%d rows" % n
    if kind == "count_multi":
        tables = _staffed(page.tables)
        if not tables:
            return False, "no table carries an open requisition column"
        for value, want in S["expected_by_value"].items():
            seen = {}
            for h, rows in tables:
                fi = _col(h, S["filter_column"])
                for r in rows:
                    key = next((c for c in r if re.fullmatch(S["key_re"], _norm(c))), None)
                    if key is None or fi is None or fi >= len(r):
                        continue
                    if _leading(r[fi], value):
                        seen[_norm(key)] = True
            notes.append("%s: %d distinct keys, expected %d" % (value, len(seen), want))
            metrics[value] = len(seen)
            if len(seen) != want:
                return False, "%s counts %d, expected %d" % (value, len(seen), want)
            summary = (S.get("summary_by_value") or {}).get(value)
            if summary and not re.search(summary, _norm(_prose(page.body))):
                return False, "the tables carry %d for %s but the summary does not state it" % (want, value)
        return True, "every department count matches and is stated"
    if kind == "absent":
        tables = _staffed(page.tables)
        if not tables:
            return False, "no table carries an open requisition column"
        hits = _keyed_rows(tables, S["keys"])
        if hits:
            return False, "%r sits on a staffed-role table" % (S["keys"][0],)
        whole = _norm(page.body)
        named = [m for m in S["mentions"]
                 if re.search(r"(?<![a-z0-9])%s(?![a-z0-9])" % re.escape(_norm(m)), whole)]
        notes.append("mentions found: %r" % named)
        if not named:
            return False, "absent from the tables but never named as a reconciling item"
        return True, "absent from the tables and named"
    if kind == "no_rows":
        tables = _staffed(page.tables)
        if not tables:
            return False, "no table carries an open requisition column"
        bad = [r for h, rows in tables for r in rows if any(re.fullmatch(S["key_re"], _norm(c)) for c in r)]
        if bad:
            return False, "%d staffed-role rows match %r" % (len(bad), S["key_re"])
        whole = _norm(page.body)
        if not re.search(S["mention_re"], whole):
            return False, "no row matches but the page never names the class as a reconciling item"
        return True, "no matching rows and the class is named"
    if kind == "summary":
        prose = _norm(_prose(page.body)) if S.get("prose_only") else _norm(page.body)
        if re.search(S["regex"], prose):
            return True, "the statement is present"
        return False, "no statement matches %r" % S["regex"]
    if kind == "vocab":
        cells, bad = 0, []
        for h, rows in page.tables:
            i = _col(h, S["column"])
            if i is None:
                continue
            for r in rows:
                cell = r[i] if i < len(r) else ""
                cells += 1
                if not any(_leading(cell, v) for v in S["allowed"]):
                    bad.append(cell)
        metrics["cells"] = cells
        if not cells:
            return False, "no table carries a %r column" % S["column"]
        if bad:
            return False, "%d cells outside the vocabulary, first %r" % (len(bad), bad[0])
        return True, "%d cells inside the vocabulary" % cells
    if kind == "dates":
        body = page.body
        iso = re.findall(r"\b\d{4}-\d{2}-\d{2}\b", body)
        spelled = re.findall(r"\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?\s+\d{1,2}(?!\d)"
                             r"(?:st|nd|rd|th)?,?\s+\d{4}", body, flags=re.I)
        dmy = re.findall(r"\b\d{1,2}\.\d{1,2}\.\d{4}\b", body)
        us = re.findall(r"\b\d{2}/\d{2}/\d{4}\b", body)
        metrics["us_dates"] = len(us)
        if iso or spelled or dmy:
            return False, "dates outside MM/DD/YYYY: %r" % (iso + spelled + dmy)[:3]
        if not us:
            return False, "no MM/DD/YYYY date on the page"
        return True, "%d dates, all MM/DD/YYYY" % len(us)
    return False, "unknown check kind %r" % kind


def check(ctx):
    notes, metrics = [], {}
    titles = SPEC["pages"]

    def fail(reason):
        return {"passed": False, "details": "\n".join(notes + ["", "FAILED - " + reason]),
                "metrics": metrics}

    try:
        verdicts = []
        for title in titles:
            pages = _load_pages(ctx, title, notes)
            if not pages:
                return fail("no page titled %r" % title)
            for p in pages:
                ok, why = _run(SPEC["kind"], p, notes, metrics)
                notes.append("page %r: %s - %s" % (title, "ok" if ok else "NO", why))
                verdicts.append(ok)
        # every row carrying the title has to satisfy: a wrong duplicate leaves the wiki wrong
        if verdicts and all(verdicts):
            return {"passed": True, "metrics": metrics,
                    "details": "\n".join(notes + ["", "PASSED - %d page row(s) satisfy"
                                                  % len(verdicts)])}
        return fail("%d of %d page rows fail" % (verdicts.count(False), len(verdicts)))
    except Exception as exc:
        notes.append("unexpected error: %s: %s" % (type(exc).__name__, str(exc)[:300]))
        return fail("the check could not complete; see the error above")
